### ISSUE TITLE
onboardType Web missing?

### ISSUE THREAD

**Issue by cokes518** [helium/maker-starter-app#13]
I was cleaning up the docs to add the maker app, and there's no maker app equivalent for web onboarding. https://github.com/helium/maker-starter-app/blob/main/src/makers/example/hotspots.ts#L6

**Comment by niamiot** [comment]
As far As I understand, web onboarding seems supported (OnBoardType can be 'WEB')....

**Comment by cokes518** [comment]
thanks for the catch. closing.
