### ISSUE TITLE
got an error when compile for android

### ISSUE THREAD

**Issue by lifei1245** [helium/maker-starter-app#19]
## Context
- react-native-ble-plx: 2.0.3
- react-native:0.66.3
- react:17.0.1
- Platform: Android
- Android Studio: Arctic Fox 2020.3.1 Patch3

JS logs:
```
* What went wrong:
Could not determine the dependencies of task ':app:mergeDebugAssets'.
> Could not resolve all task dependencies for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve project :react-native-ble-plx.
     Required by:
         project :app
      > No matching configuration of project :react-native-ble-plx was found. The consumer was configured to find a runtime of a component, as well as attribute 'com.android
.build.api.attributes.BuildTypeAttr' with value 'debug' but:
          - None of the consumable configurations have attributes.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2m 54s

```
 is there any solution for this?

**Comment by tyler-whitman** [comment]
@lifei1245 for some reason the build is not finding the `react-native-ble-plx` library, which OS are you building on? Can you trying running `yarn clean-install` in the root of the project and then run `yarn android` again.

**Comment by lifei1245** [comment]
@tyler-whitman I built on Windows 10 , I open the android project in android studio directly ,it seems the settings isn't correct
```
No variants found for ':react-native-ble-plx'. Check build files to ensure at least one variant exists.
```
is there something else need to do? 
and it can't find ``com.polidea.reactnativeble.BlePackage`` in MainApplication when I use `react-native run-android`

**Comment by tyler-whitman** [comment]
Did you try `yarn clean-install` in the root of the project and then running `yarn android`. This project uses React Native and doesn't need to be opened in Android Studio. You need to make sure to run the javascript install commands to pull down all the libraries. 

You can also follow the project readme for detailed setup and getting started instructions. If those are not working for you, please let me know where you are getting stuck.

**Comment by lifei1245** [comment]
@tyler-whitman I removed temp folders manually(C:/Users/user/AppData/Local/temp and node_modules), because `rm -rf` is not available on windows and the folder system is not the same with macOS or linux  and then run  `yarn cache clean && yarn install` successfully

But I still got the same error,have you built successfully on windows before?

**Comment by lifei1245** [comment]
I resolve this by add reposity to the gradle file of react-native-ble-plx

**Comment by boern** [comment]
@lifei1245 I got the same error, can you share  how to solve it ?

**Comment by lifei1245** [comment]
@boern  jcenter is no longer available and google repository is not available for some area ,so adding an available repository  to `buildscript > repositories` like `mavenCentral()`  will solve the problem(tip: update the gradle version if necessary).
