### ISSUE TITLE
Getting invalid link screen when testing transfer hotspot.

### ISSUE THREAD

**Issue by CesarAHernandez** [helium/maker-starter-app#21]
I am testing transfer hotspot. When I try to transfer a hotspot I get the screen below.

![IMG_0629](https://user-images.githubusercontent.com/11858501/154537236-6879a026-4909-4c0e-a281-44529ee0bbac.PNG)

**Comment by tyler-whitman** [comment]
The reason you are getting this error is because the Hotspot App version you are using does not have the transfer deeplink code. This won't be available until Hotspot App version 3.11.0, or you can build the Hotspot App locally and test that way. https://github.com/helium/hotspot-app
