### ISSUE TITLE
How to get keypair for API Authorization

### ISSUE THREAD

**Issue by estherlinlin** [helium/maker-starter-app#22]
### Problem

Our team is developing maker-app base on this repository.
Currently we are migrating update and transfer hotspot features from helium-app,
but encounter an issue 401 authorization fail, when calling API from wallet endpoint  `https://wallet.api.helium.systems/api`

```
status:401 message: POST url:https://wallet.api.helium.systems/api/transactions]
```

We need `keypair` to generate token for the Authorization header in api request, 
(keypair are also needed when calling transaction APIs)
but we only could retrieve `walletLinkToken` when user sign in by linking helium account.

**How can we get the `keypair` for API authorization and transaction signing?
Or is there a way to get `keypair` from `walletLinkToken`?**
<br>

### Related Code

`src/utils/secureAccount.ts`
```
export const createKeypair = async (
  givenMnemonic: Mnemonic | Array<string> | null = null,
) => {
  ...
  const { keypair: keypairRaw, address } = await Keypair.fromMnemonic(mnemonic)

  await Promise.all([
    setSecureItem('mnemonic', JSON.stringify(mnemonic.words)),
    setSecureItem('keypair', JSON.stringify(keypairRaw)),
    setSecureItem('address', address.b58),
  ])
}

export const getKeypair = async (): Promise<Keypair | undefined> => {
  const keypairStr = await getSecureItem('keypair')
  if (keypairStr) {
    const keypairRaw = JSON.parse(keypairStr)
    return new Keypair(keypairRaw)
  }
}
```

**Comment by estherlinlin** [comment]
We found the solution in the latest update. Thanks!

**Comment by MykhailoMashchenko** [comment]
Hi, we are currently trying to get this keypair keys to work with https://wallet.api.helium.systems/api. Any help with that? Thx
