### ISSUE TITLE
Invalid link from transferring hotspot 

### ISSUE THREAD

**Issue by ainno-chris-lin** [helium/maker-starter-app#23]
Hi Teams,

We test this new feature (transfer hotspot) and encounter the following problem:
When we key in our hotspot address and new owner address and it will redirect to helium hotspot app and show the invalid link page.
Do you have any suggestion for this?

![S__16293924](https://user-images.githubusercontent.com/64433709/155465468-1fb5de7f-5346-4693-853e-3a7577590435.jpg)

**Comment by cokes518** [comment]
Hi, you'll have to wait for app release 3.11 for transfer hotspot deeplink to work. It will be out this week.

**Comment by ainno-chris-lin** [comment]
Got it, we will wait for app release and test it again, thank you!!!
