### ISSUE TITLE
The different results of scanning QR code between Helium hotspot app and Helium maker-starter-app

### ISSUE THREAD

**Issue by ainno-chris-lin** [helium/maker-starter-app#24]
Hi Teams,

When we test on QR code on-boarding feature, we encounter the different result of scanning QR code between Helium hotspot app and Helium maker-starter-app.
Helium hotspot app scan our QR code is OK and show confirm information page.
But Helium maker-starter-app scan our QR code is failed and show invalid link.
Our QR code is generated by these instructions (https://docs.helium.com/mine-hnt/full-hotspots/become-a-maker/hotspot-integration-testing/#generate-an-add-hotspot-transaction).
Is there any suggestion? Thanks!

**Comment by cokes518** [comment]
Can you show us the QR code so we can debug? Is this on iOS or Android? Are you a Maker? Can you show us any screenshots? There's not a lot of information provided in this bug report.

**Comment by matthewcarlreetz** [comment]
@ainno-chris-lin Are you using the same QR code between the two apps? The maker app will need a different scheme `makerappscheme://add_gateway/your_txn`

**Comment by ainno-chris-lin** [comment]
@matthewcarlreetz , yes, I use the same QR code between the two apps, so I need use the makerappscheme, not helium scheme. Thanks, I will use makerappscheme and try it again.

**Comment by nssprite** [comment]
Is there a conclusion on this question? @ainno-chris-lin
