### ISSUE TITLE
The assist asserting gateway location is unsuccessful during add a new hotspot

### ISSUE THREAD

**Issue by 63669733** [helium/maker-starter-app#27]
Hello, this is our current problem 1. The assist asserting gateway location is unsuccessful during add a new hotspot (you need to set the location again after successful add hotspot, you can set it once for free) 2. The antenna setting during add hotspot is unsuccessful (you need to consume DC to update the antenna after successful add hotspot). Thank you!

**Comment by cokes518** [comment]
Sounds like the assert_location bundled with add_gateway regressed. we'll look into it.

can you tell us the Hotspot name and screenshots please?
