### ISSUE TITLE
Android build error: Execution failed for task ':helium_react-native-sdk:compileDebugKotlin'.

### ISSUE THREAD

**Issue by LeoUbl** [helium/maker-starter-app#48]
Up to a month ago I could build my android app, but since two weeks ago I get this error without editing anything in my project.
I also just tried to build the app from your current github project and I still get the error.
I'm using ubuntu terminal to build the app.

Steps to reproduce the error:
1) Clone the project from your github
2) I assume you have already set up react native on your machine, so skip to "Installing" section and follow those steps.
3) cd ~/maker-starter-app ; mkdir android/app/src/main/assets (this folder is used during android building)
4) Build android app. These are the commands I use in the terminal
5) cd ~/maker-starter-app ; cd android ; ./gradlew clean ; cd ..
6) react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res
7) react-native run-android

Steps 5 and 6 return some warnings, step 7 returns errors like:
`e: Incompatible classes were found in dependencies. Remove them from the classpath or use '-Xskip-metadata-version-check' to suppress errors
e: /home/my_ubuntu_username/.gradle/caches/transforms-3/2cfe106a332c6a6f2245988cf5920bcb/transformed/jetified-kotlin-stdlib-common-1.6.10.jar!/META-INF/kotlin-stdlib-common.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.1.15.`

The final error says:
```text
FAILURE: Build completed with 2 failures.

1:Task failed with an exception.
What went wrong:
Execution failed for task ':helium_react-native-sdk:compileDebugKotlin'.
Compilation error. See log for more details

Try:
Run with --stacktrace option to get the stack trace.
Run with --info or --debug option to get more log output.
Run with --scan to get full insights.

2: Task failed with an exception.
What went wrong:
java.lang.StackOverflowError (no error message)

Try:
Run with --stacktrace option to get the stack trace.
Run with --info or --debug option to get more log output.
Run with --scan to get full insights.

Get more help at https://help.gradle.org/

BUILD FAILED in 1m
```

I found a similar issue on github which seems got fixed, here's the link: https://github.com/segmentio/analytics-react-native/issues/645

Can you please fix this problem on your github project too?
Thanks in advance

**Comment by matthewcarlreetz** [comment]
@LeoUbl Could you try this #49 branch and let me know if you are still facing the issue?
https://github.com/helium/maker-starter-app/tree/feature/upgrade-rn-0.70.6

**Comment by Corniot** [comment]
> @LeoUbl Could you try this #49 branch and let me know if you are still facing the issue? https://github.com/helium/maker-starter-app/tree/feature/upgrade-rn-0.70.6



> @LeoUbl Could you try this #49 branch and let me know if you are still facing the issue? https://github.com/helium/maker-starter-app/tree/feature/upgrade-rn-0.70.6

I tried the latest code, but still show this error. What version of Android SDK and build tools are you using?

**Comment by Corniot** [comment]
@LeoUbl I solved the problem
First, download the latest code
Second, Add kotlinVersion = "1.6.10" and classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlinVersion" these code in build.gradle. Look at the picture below.
![image](https://user-images.githubusercontent.com/119033589/206828668-2e9ffa54-1083-47c8-bfce-fe4cc62eabd8.png)

**Comment by LeoUbl** [comment]
Thank you very much!!! @Corniot . Using the latest code and adding the kotlinVersion fixed the problem.
@matthewcarlreetz I think you should include the kotlinVersion in the next code version as soon as possible because the current version isn't enough to fix the problem. Thanks.

**Comment by cagataykula** [comment]
> @LeoUbl I solved the problem First, download the latest code Second, Add kotlinVersion = "1.6.10" and classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlinVersion" these code in build.gradle. Look at the picture below. ![image](https://user-images.githubusercontent.com/119033589/206828811-77ac5092-5910-4eb0-a2c4-99f174ba9cf3.png)

this is solving the issue, thanks @Corniot  👍

**Comment by LeoUbl** [comment]
I'm closing this since the latest version seems to compile correctly. Thanks everyone
